### PR TITLE
🚸(frontend) improve prejoin UX

### LINKED ISSUE #324: Blinking effect when toggling microphone
## Bug Report

**Problematic behavior**
Blinking effect when toggling microphone

**Expected behavior/code**
The video flux should not blinking while toggling microphone.

**Steps to Reproduce**

https://github.com/user-attachments/assets/9ef0b1bc-7f6f-4343-8a43-cf3d561b44dc

**Possible Solution**
It may be caused be a re rendering of the video element?

### PR DESCRIPTION
**Pull request by lebaudantoine**
[Enhancements proposed in a short loom](https://www.loom.com/share/201fbaf367e44b37ac159ca6423db5d2)

- Always enable camera/mic by default (like Google Meet)
- Fix video state transitions and add visual feedback
- Simplify form using React Aria components
- Reduce shadow intensity for better visual balance

It closes #324

### CODE REVIEW

**Comment by lebaudantoine** [comment]
I've noticed another issue, we didn't properly disable the long press. We can enable the mic toggle button using a long press on the space bar … 

I don't know if I'll spend much time on it, should we replace this toggle select component by the same UX as Google Meet ? Wdyt @NathanVss ?

File: src/frontend/src/features/rooms/components/Join.tsx [hunk 1]
```diff
@@ -232,67 +158,60 @@ export const Join = ({
...
                 <video
                   ref={videoEl}
                   width="1280"
                   height="720"
-                  data-lk-facing-mode={facingMode}
                   className={css({
                     display: 'block',
-                    width: '100%',
-                    height: '100%',
+                    width: '102%',
```
Comment (NathanVss) [inline src/frontend/src/features/rooms/components/Join.tsx:177]: Why so? To prevent shitty blurring on the edges?

File: src/frontend/src/features/rooms/components/Join.tsx [hunk 2]
```diff
@@ -232,67 +158,60 @@ export const Join = ({
...
-                padding: '1.5rem',
-                gap: '1rem',
-              })}
-            >
+
+            <HStack justify="center" padding={1.5}>
               <SelectToggleDevice
                 source={Track.Source.Microphone}
-                initialState={audioEnabled}
+                initialState={true}
```
Comment (NathanVss) [inline src/frontend/src/features/rooms/components/Join.tsx]: Why are you not using audioEnabled?

File: src/frontend/src/features/rooms/components/Join.tsx [hunk 3]
```diff
@@ -302,21 +221,18 @@ export const Join = ({
               />
               <SelectToggleDevice
                 source={Track.Source.Camera}
-                initialState={videoEnabled}
+                initialState={true}
```
Comment (NathanVss) [inline src/frontend/src/features/rooms/components/Join.tsx]: Ditto

File: src/frontend/src/primitives/Form.tsx [hunk 4]
```diff
@@ -25,6 +26,7 @@ export const Form = ({
     event: FormEvent<HTMLFormElement>
   ) => void
   submitLabel: string
+  submitFullWidth?: boolean
```
Comment (NathanVss) [inline src/frontend/src/primitives/Form.tsx]: I tend to prefer using submitProps: ButtonProps in those situations, it scales better when adding multiple levels of customization. But this is a nitpick.

File: src/frontend/src/features/rooms/components/Join.tsx [hunk 5]
```diff
@@ -28,160 +21,93 @@ export const Join = ({
...
-    } else {
-      log.warn('Validation failed with: ', userChoices)
-    }
+    onSubmit({
+      audioEnabled: audioEnabled,
+      videoEnabled: videoEnabled,
+      audioDeviceId: audioDeviceId,
+      videoDeviceId: videoDeviceId,
+      username: username,
+    })
```
Comment (NathanVss) [inline src/frontend/src/features/rooms/components/Join.tsx]:
```suggestion
onSubmit({
      audioEnabled,
      videoEnabled,
      audioDeviceId,
      videoDeviceId,
      username,
    })
    
```


?

File: src/frontend/src/features/rooms/components/Join.tsx (hunk 1 above)
Comment (lebaudantoine) [reply src/frontend/src/features/rooms/components/Join.tsx:177]: On my screen I got some visual artifact on the border. We could see 1px of the background color around the video element.

File: src/frontend/src/primitives/Form.tsx (hunk 4 above)
Comment (lebaudantoine) [reply src/frontend/src/primitives/Form.tsx]: agree

Comment (lebaudantoine) [reply src/frontend/src/primitives/Form.tsx]: done
